### ISSUE TITLE
Can't push to personal public repo

### ISSUE THREAD

**Issue by kkoomen** [petersalomonsen/wasm-git#100]
Hi,

I have a project that spawns a `Worker` instance and inside there I have the following code:

```ts
let accessToken = null;
XMLHttpRequest.prototype._open = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open = function(method, url, async, user, password) {
  this._open(method, url, async, user, password);
  this.setRequestHeader('Authorization', `Bearer ${accessToken}`);
}

// Libgit will add two global variables:
// - Module: the libgit2 module
// - FS: the filesystem
self.importScripts('../vendor/libgit2.js');


class API {
  /**
   * Contains a reference to the libgit2 filesystem.
   * @type {FS}
   */
  fs = null;

  /**
   * Contains a reference to the libgit2 module.
   * @type {Module}
   */
  lg = null;

  /**
   * The name of the directory where to clone the repo in.
   * @type {string}
   */
  repoDir = 'project';

  constructor(options) {
    accessToken = options.accessToken;
    this.repoLink = options.repoLink;

    this.readyCallback = options.readyCallback;

    this._init();
  }

  async _init() {
    this.lg = await (new Promise(resolve => {
      Module.onRuntimeInitialized = () => {
        console.log('Initialized libgit2 successfully');
        this.readyCallback();
        resolve(Module);
      }
    }));

    this.fs = FS;

    this.clone('http://localhost:5000/kkoomen/ide-test');
  }

  clone(link) {
    console.log('Cloning', link);
    this.lg.callMain(['clone', link, this.repoDir]);
    this.fs.chdir(this.repoDir);
    this.fs.syncfs(false, () => {
      console.log(this.repoDir, 'stored to indexeddb');
    });
    console.log('Dir contents:', this.fs.readdir('.'));

    const filename = 'README.md';
    const filecontents = 'Hello World';
    this.fs.writeFile(filename, filecontents);
    console.log('File contents:', this.fs.readFile(filename));
    console.log('Dir contents:', this.fs.readdir('.'));

    this.lg.callMain(['add', '--verbose', filename]);
    this.lg.callMain(['commit', '-m', `Added ${filename}`]);
    this.lg.callMain(['push']);
  }
}

// =============================================================================
// Worker message handling.
// =============================================================================

let api;
let port;

const onAnyMessage = async event => {
  switch (event.data.id) {
    case 'constructor':
      const { port, ...args } = event.data.data;
      port.onmessage = onAnyMessage;
      api = new API({
        ...args,

        readyCallback() {
          port.postMessage({ id: 'ready' });
        },
      });
      break;
  }
};

self.onmessage = onAnyMessage;
```

The libgit2.js and libgit2.wasm are the ones from https://unpkg.com/wasm-git@0.0.2/

The `accessToken` is a personal access token that I generated through GitHub > Settings > Developer Settings > Personal Access Tokens. I tested my access token by doing an API call to api.github.com/user with `Bearer <token>` and I got a successful response, so the token is not the problem here.

I am using the proxy that you suggested [here](https://github.com/petersalomonsen/wasm-git/issues/20), but this is the output from the `clone()` function in the console as of right now:

<img width="644" alt="image" src="https://github.com/user-attachments/assets/e7679028-532d-4392-a8d7-353b9d471d91">

for somehow, I'm constantly getting `ERROR 12: bad packet length` and the changes are not pushed to my personal public repo. Any idea what the problem is?

P.s. can you perhaps also explain what `FS.syncfs` exactly does and when it is needed exactly?

Thanks in advance.

**Comment by kkoomen** [comment]
Based on @petersalomonsen his suggestion in #101 I have rewritten the worker code to be the following:

```ts
let accessToken = null;
XMLHttpRequest.prototype._open = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open = function(method, url, async, user, password) {
  this._open(method, url, async, user, password);
  this.setRequestHeader('Authorization', `Bearer ${accessToken}`);
}

class API {
  /**
   * Contains a reference to the libgit2 filesystem.
   * @type {FS}
   */
  fs = null;

  /**
   * Contains a reference to the libgit2 module.
   * @type {Module}
   */
  lg = null;

  /**
   * The name of the directory where to clone the repo in.
   * @type {string}
   */
  repoDir = 'project';

  constructor(options) {
    accessToken = options.accessToken;
    this.repoLink = options.repoLink;

    this._init().then(() => {
      options.readyCallback();
    });
  }

  async _init() {
    const lg2mod = await import(new URL('../vendor/lg2.js', import.meta.url));
    this.lg = await lg2mod.default();
    this.fs = this.lg.FS;
    this.fs.writeFile('/home/web_user/.gitconfig',
      `[user]
    name = "Test user"
    email = "test@example.com"`);


    this.clone('http://localhost:5000/kkoomen/ide-test');
  }

  clone(link) {
    console.log('Cloning', link);
    this.lg.callMain(['clone', link, this.repoDir]);
    this.fs.chdir(this.repoDir);
    this.fs.syncfs(false, () => {
      console.log(this.repoDir, 'stored to indexeddb');
    });
    console.log('Dir contents:', this.fs.readdir('.'));

    const filename = 'README.md';
    const filecontents = 'Made through gitfs in uvapl!';
    this.fs.writeFile(filename, filecontents);
    console.log('File contents:', this.fs.readFile(filename));
    console.log('Dir contents:', this.fs.readdir('.'));

    this.lg.callMain(['add', '--verbose', filename]);
    this.lg.callMain(['commit', '-m', `Added ${filename}`]);
    this.lg.callMain(['push']);
  }
}

// // =============================================================================
// // Worker message handling.
// // =============================================================================

let api;


self.onmessage = (event) => {
  switch (event.data.id) {
    case 'constructor':
      api = new API({
        ...event.data.data,

        readyCallback() {
          postMessage({ id: 'ready' });
        },
      });
      break;
  }
};
```

however and I have created a new lg2.js and lg2.main v1.8.1 build, but the same error appear. I am sure that the token is valid, as I have created it and checked all permissions to be available (just for testing purposes), but still, no chance. @petersalomonsen Do you have any idea?

**Comment by petersalomonsen** [comment]
Hi, I haven't got the chance to test your code yet, but I can answer regarding FS.syncfs which is a feature of Emscripten for the IndexedDB file system. You can read more about it here: https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.syncfs

An example of pushing can be found in the test here: https://github.com/petersalomonsen/wasm-git/blob/master/test-browser/remote.spec.js#L45

Example of pushing with credentials can be found in the WebAssembly music project: https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitclient.spec.js#L109

Hope that these examples give you some idea on how to write it.

**Comment by kkoomen** [comment]
@petersalomonsen would be nice if you can test it and see why I'm getting the error messages. I've written the code based on the remote.spec.js already in the example above, but I can't get it to work unfortunately. I hope you can test this soon ^^

**Comment by kkoomen** [comment]
@petersalomonsen I tried to debug this again but it's a tough one. The response I'm getting is `No anonymous write access.` while I did wrote the .gitconfig with my own credentials. Right now I'm sending with `Authorization: Basic <base64(username:access-token)>`, but still no diference. Here's my debugging output:

<img width="679" alt="image" src="https://github.com/user-attachments/assets/387b9bff-1d31-479d-a1e8-a2c16b9954cc">

with the `clone` function being like this:

```
  clone(link) {
    console.log('Cloning', link);
    this.lg.callMain(['clone', link, this.repoDir]);
    this.fs.chdir(this.repoDir);
    this.fs.syncfs(false, () => {
      console.log(this.repoDir, 'stored to indexeddb');
    });
    console.log('Dir contents:', this.fs.readdir('.'));

    const filename = 'README.md';
    const filecontents = 'Made through gitfs in uvapl!';
    this.fs.writeFile(filename, filecontents);
    console.log('File contents:', this.fs.readFile(filename));
    console.log('Dir contents:', this.fs.readdir('.'));

    this.lg.callMain(['add', '--verbose', filename]);
    this.lg.callMain(['commit', '-m', `Added ${filename}`]);

    this.lg.callMain(['log'])
    this.lg.callMain(['push', '--force'])
  }
```

**Comment by petersalomonsen** [comment]
what does your github proxy look like? Does it forward the personal access token?

**Comment by kkoomen** [comment]
@petersalomonsen Can you re-read my original message? I clearly mentioned the following:
> I am using the proxy that you suggested [here](https://github.com/petersalomonsen/wasm-git/issues/20), but this is the output from the clone() function in the console as of right now:

**Comment by petersalomonsen** [comment]
All right, there you can see from the `options` object, that the proxy does not forward any headers, which means your access token is not forwarded. If you add the header with your personal access token to the proxy, that should make a difference.
