### ISSUE TITLE
How to make a build compatible for Workers?

### ISSUE THREAD

**Issue by kkoomen** [petersalomonsen/wasm-git#101]
Hi,

When I run `./emscriptenbuild/build.sh Release` it creates an `lg2.js` for the browser, as it uses on line 3: `var _scriptName = import.meta.url;` but I'm using a worker where I'm loading the lg2 js file, so this is not supported inside a worker instance, however the lg2.js from the CDN used at the demo site, being https://unpkg.com/wasm-git@0.0.2/lg2.js does work inside my worker. How is the lg2.js on unpkg created exactly?

Thanks.

**Comment by petersalomonsen** [comment]
Hi, see the [test-browser](./test-browser) folder where the worker setup also can be found. Here is the worker source: https://github.com/petersalomonsen/wasm-git/blob/master/test-browser/worker.js

To see how the releases are created, you can look into the github actions workflow which can be found here: https://github.com/petersalomonsen/wasm-git/blob/master/.github/workflows/publish.yml
