### ISSUE TITLE
exception thrown: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load ...

### ISSUE THREAD

**Issue by trusktr** [petersalomonsen/wasm-git#20]
I tried pasting this URL in the live example: https://github.com/lume/glas

Normally, when I use `git` at the command line, I am able to use a URL like that for the remote origin.

f.e. `git clone https://github.com/lume/glas` works in my terminal.

**Comment by petersalomonsen** [comment]
yes this is because of CORS. github does not return the header `Access-Control-Allow-Origin: *`. Only browsers check for this header, git on the command line does not (it's up to the client to honor this, the server just send the header). That's why I created my own git-server at https://wasm-git.petersalomonsen.com

If you want to clone from github you'll need a proxy that sends this header so that remote origins are allowed. Here's a simple proxy in nodejs:

```
const http = require('http');
const https = require('https');
const fs = require('fs');

function onRequest(request, response) {
    let path = request.url.substring(1);
    console.log(path);

    response.setHeader('Access-Control-Allow-Origin', '*');
    response.setHeader('Access-Control-Allow-Headers', '*');

    if( path.indexOf('git-upload') > -1 ||
        path.indexOf('git-receive') > -1) {  
        const options = {
            hostname: 'github.com',
            port: 443,
            path: request.url,
            method: request.method,
        };

        console.log(`Proxying ${options.method} request to ${options.hostname} with path ${options.path}`);
        const proxy = https.request(options, function (res) {
            res.pipe(response, {
            end: true
            });
        });

        request.pipe(proxy, {
            end: true
        });
    } else {
        if(path === '') {
            path = 'index.html';
        }

        if(fs.existsSync(path)) {
            if(path.indexOf('.js') === path.length-3) {
                response.setHeader('Content-Type', 'application/javascript');
            } else if(path.indexOf('.wasm') === path.length-5) {
                response.setHeader('Content-Type', 'application/wasm');
            }
            response.end(fs.readFileSync(path));
        } else {
            response.statusCode = 404;
            response.end('');
        } 
    }
}

http.createServer(onRequest).listen(5000);
```

start this on your local machine, and then you can clone from http://localhost:5000/lume/glas

**Comment by petersalomonsen** [comment]
here's a screen recording I just made: https://youtu.be/EYccHfaG6ZM

**Comment by maks** [comment]
Yes lack of CORS from the big Git providers has been a real nuisance for a very long time, heres my [asking for it from Bitbucket back in 2014](https://jira.atlassian.com/browse/BCLOUD-8846) !

I vaguely remember a similar request was made to Github that went no where too.

Also for local development at least, you [could try this](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) BUT I HAVE NOT tried it myself so please use with caution!
