### ISSUE TITLE
`lg.callMain(['checkout', '--', 'a-deleted-file.txt'])` failed

### ISSUE THREAD

**Issue by ylc395** [petersalomonsen/wasm-git#29]
version: 0.0.6

I'm using wasm-git with NODEFS in a worker in  a electron render process. `git checkout -- a-deleted-file.txt` will cause a crash when:

Step 0: mount Emscripten FS with NODEFS on a physical directory -> `FS.chdir` -> `lg.callMain(['init', '.'])` -> `lg.callMain(['status'])`

Step 1: use Noejs FS API(outside of worker) to create a file in the physicial directory, and `lg.callMain(['add', '.'])` -> `lg.callMain(['commit', '-m', 'commit message'])` -> `lg.callMain(['status'])`

Step 2: use Nodejs FS API(outside of worker) to delete the file in the physicial direcotry, and `lg.callMain(['add', '.'])` -> `lg.callMain(['status'])` -> `lg.callMain(['checkout', '--',  'the-deleted-file.txt'])` -> `lg.callMain(['status'])`. The deleted file will be restored in physicial direcotry successfully.

Step 3: repeat Step 2. And cause crash when `lg.callMain(['checkout', '--',  'the-deleted-file.txt'])`

<img width="666" alt="图片" src="https://user-images.githubusercontent.com/12264626/115491291-46b31b00-a292-11eb-9c4f-52631927e6a7.png">

Am I using `checkout` feature in a wrong way? In real git, if we want to restore a deleted file in working tree, we should use `git checkout HEAD -- the-deleted-file.txt`, but wasm-git seems to do not support `lg.callMain(['checkout', 'HEAD', '--', 'the-deleted-file.txt'])`, so I just omit `'HEAD'.`

**Comment by petersalomonsen** [comment]
the `checkout` is based on the libgit2 examples, and I've added the possibility to use `--` in order to discard changes, but not `checkout HEAD -- file.txt`.

You can see my additions to checkout in the pull request here: https://github.com/libgit2/libgit2/pull/5609

This is not yet merged though, feel free to improve it or comment.

**Comment by ylc395** [comment]
nice, I will try to dig into libgit2.
