### ISSUE TITLE
How to access result of "git status"?

### ISSUE THREAD

**Issue by alexciesielski** [petersalomonsen/wasm-git#34]
Hey, I'm liking this library more and more, it seems it's much more performant already than isomorphic-git.
Although It's currently lacking documentation I will gladly write some if this library turns out to be performant enough for our product.

I'm following the [webworker example](https://github.com/petersalomonsen/wasm-git/blob/master/examples/example_webworker.js) and I'm calling `lg.callMain(['status'])` but it doesn't return anything other than logging to the console so I'm wondering how I can check the result of git status programatically?

**Comment by ciesielskico** [comment]
Actually just running `lg.callMain(['add', '.'])` did the trick, still I'm missing the ability to check the status of the files in git

**Comment by petersalomonsen** [comment]
since wasm-git commands are based on [libgit2 examples](https://github.com/libgit2/libgit2/tree/main/examples), these are only printing their output to the console. However you can capture this output e.g. like this:

```
var Module = {
  locateFile: function (s) {
    return 'https://unpkg.com/wasm-git@0.0.4/' + s;
  },
  'print': function (text) {
    if (captureOutput) {
      stdout += text + '\n';
    }
    console.log(text);
  },
  'printErr': function (text) {
    if (captureOutput) {
      stderr += text + '\n';
    }
    console.error(text);
  }
};
```

and then you can use it for `git status` for example like this:

```
function repoHasChanges() {
    callAndCaptureOutput(['status']);

    if (stdout.indexOf('Changes to be committed:') > -1) {
      return true;
    } else {
      return false;
    }
  }
```

See the full example in the [WebAssembly Music](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitworker.js#L60) repository, where I use wasm-git for offline editing of music-code (and synchonizing with the server when online).

**Comment by ciesielskico** [comment]
Thanks for the quick response.
I copied your code but for some reason the output is not being capture.

I'm on wasm-git@0.0.6 though, does that make a difference?

Even when commenting out console.log the output is still being written to the console and stdout stays empty (omitting onmessage listener for brevity).

```
let stdout = '';
let stderr = '';
let captureOutput = false;

console.log('Stupid worker started');

const webWorkerAction = (action) => {

  const { type, params } = action;
  switch (type) {
    case 'init': {
      return new Promise((resolve) => {
        importScripts('lg2.js');

        Module['onRuntimeInitialized'] = () => {
          lg = Module;
          Module['print'] = (text) => {
            // if (captureOutput) {
            stdout += text + '\n';
            // }
            // console.log(text);
          };
       })
   }
});
```

**Comment by petersalomonsen** [comment]
what does the webpack bundle look like ? has it minified `var Module`?. You could try by declaring it up front e.g. `declare var Module;` or even `self['Module'] = {.... `

The important is that Emscripten sees that `Module` is already defined when you import it.

Regarding Angular, I did use Angular myself for my first attempts with compiling libgit2 to wasm. Back then Angular did not have worker support, so I just defined the worker code inside a function and used Function.toString for extracting the source into a Blob and ObjectURL for loading as a worker. Haven't tried with Angular recently, but I guess if you make sure that it is defined as `Module` in the bundle then it should work.
