### ISSUE TITLE
Question: Use in a VSCode extension 

### ISSUE THREAD

**Issue by AntonOfTheWoods** [petersalomonsen/wasm-git#39]
It can be a pain for non-techies to install git on non-persistant public (Windows) computers and it would be great to be able to use VSCode to properly interact with Github without local git. It would also allow for some cool stuff with the new vscode.dev, given you can now dev on local folders.

Is there any fundamental reason why an extension couldn't use this project to provide the basic features of interaction with Github (or any git...)?

**Comment by petersalomonsen** [comment]
If you create an extension for VSCode you'd probably want to use [libgit2](https://github.com/libgit2/libgit2) directly ( which is the library that powers wasm-git ).

It might make sense to use wasm-git though if you have a WebAssembly/Javascript runtime available, since then you don't need builds for different platforms.

**Comment by AntonOfTheWoods** [comment]
> If you create an extension for VSCode you'd probably want to use [libgit2](https://github.com/libgit2/libgit2) directly ( which is the library that powers wasm-git ).

Thanks for the reply @petersalomonsen . Actually I was thinking of a pure WASM/JS runtime environment, so that the extension could be used with both normal VSCode and also vscode.dev.

To be honest, I'm surprised no one else has done this already - while I agree that most of the time you won't have to manually install git every time you want to use it, I would have thought my usecase was reasonable - student lab computers that don't have git.

Would that probably work?

**Comment by petersalomonsen** [comment]
Yes in a pure WASM/JS runtime environment it should work fine. I'm using it myself in my live coding music environment (example here: https://petersalomonsen.com/webassemblymusic/livecodev2/?gitrepo=test ), where the git repositories are hosted in my git server at https://wasm-git.petersalomonsen.com
