### ISSUE TITLE
support for lower level libgit2 APIs?

### ISSUE THREAD

**Issue by maks** [petersalomonsen/wasm-git#4]
The examples show using the higher level "porcelain" commands, but I was wondering if I am missing something on how to access the lower level "plumping" APIs, eg. [rev walking ](https://libgit2.org/libgit2/#HEAD/group/revwalk) ?

**Comment by petersalomonsen** [comment]
I would look into this then: 

https://libgit2.org/docs/guides/101-samples/#revwalk

You would of course have to extend methods exposed to javascript, but it could be as simple as annotating them with [EMSCRIPTEN_KEEPALIVE](https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=emscripten_keepalive#c.EMSCRIPTEN_KEEPALIVE)

**Comment by maks** [comment]
@petersalomonsen sorry about that, I think I wasn't very lcear in what I was asking. I guess I really had 2 questions:
1 are the low level apis already exposed from wasm ?
2 if not, are there examples on how to expose them with emscripten and use them from wasm ?

so its a no for 1 and you've pointed me in the right direction for 2 - thanks!
