### ISSUE TITLE
wasm-git general question

### ISSUE THREAD

**Issue by kgzoom** [petersalomonsen/wasm-git#42]
Hi Peter,
I'm not sure how to contact you. I tried DMing you on Twitter, but you don't accept them (@LearnWasm). I just have a few basic questions about wasm-git. I just started learning Wasm:
1. I was under the impression that some libgit2 functionality (like SSH) is not really doable in the JS runtime. Is this different in Wasm and wasm-git? Specifically, can you do all Git commands (using GitHub as your repo) over HTTPS if you have a token (instead of a password)?
2. Are there any limitations to wasm-git compared to libgit2 on a linux PC? I want to create both a client and a server in the same Webassembly runtime in a browser. In other words, I want to be able to push and pull and clone (etc...) from other browsers, and have them do the same.

**Comment by maks** [comment]
Peter can probably give a better answer, but to start with, for what you are asking for, the limitations will be due to browsers not providing any access to raw sockets, hence there are *no* SSH JS libs for browsers that dont rely on use of proxies. 

This has nothing to do with Warm, it's a webbrowser restriction, so if you chose to use a wasm implementation outside a webbrowser, this limitation would not apply, though you would still need some way to access sockets in whatever wasm engine you used.

Even if you choose to use HTTPS instead of SSH on a webbrowser with wasm libgitw, you'll find there are also limits due to CORS that you need to take into account if you try to use reps hosted at big providers eg. GitHub.

**Comment by petersalomonsen** [comment]
yes it is as @maks says. 

I can add that Emscripten ( which is used for compiling wasm-git ) provides the socket support. You can read more about it here: https://emscripten.org/docs/porting/networking.html?highlight=socket#networking

I haven't tested this for ssh though, my focus has been on http support in node and the browser (where I created dedicated transports for this).

**Comment by kgzoom** [comment]
Thanks @petersalomonsen and @maks,

I'm not interested in SSH, only HTTPS. I'm also not knowledgeable about this. So, if I'm understanding both of you correctly, wasm-git has all the Git functionality over HTTPS as long as you configure CORS properly? I really want to know if it's possible to do this with the wasm-git Wasm module out of the box.

**Comment by petersalomonsen** [comment]
As long as you configure CORS properly, then you can interact with any git server over HTTPS, and operations like clone, push, pull (fetch), works fine.

I've set up a git server without CORS restrictions here: https://wasm-git.petersalomonsen.com/

If you want to use github as your server, you'd have to provide a proxy without CORS restrictions, or on the same domain as where you run wasm-git. There's an example for that in the wasm-git repository here: https://github.com/petersalomonsen/wasm-git/blob/master/examples/webserverwithgithubproxy.js

Not sure I understand your use-cases, but at least I can say that I use it for my livecoding music app. This example here will clone the sources from a repository in the git server above (gitrepo is the query string parameter): 

https://petersalomonsen.com/webassemblymusic/livecodev2/0.0.28/?gitrepo=test

In here I do clone, push, pull, merge, commit, discard, log, diff and more..

**Comment by kgzoom** [comment]
Sorry for not being clear about my use case.

I want to use GitHub as a central store of all the IP:port ("WebRTC" type data) for each client (each node). There is no difference between client and server nodes. They all use the same codebase. The app is peer-to-peer with a centralized store: GitHub. I want the app to be able to push and pull between each other, and to Github as well.

**Comment by kgzoom** [comment]
@petersalomonsen

"If you want to use github as your server, you'd have to provide a proxy without CORS restrictions, or on the same domain as where you run wasm-git."

I think I'm not explaining myself properly. I only want to use GitHub as a repo. That's it. I want to be able to do all the things you normally do with a repo: push, pull, clone, etc. Do I need to set up a proxy for that? Or can I do that only using the wasm-git library? Because I'm only interested in writing code for the browser. Nothing outside the browser.

**Comment by maks** [comment]
@kgzoom As I said initially, the ability to use Github as a remote from within a browser has **nothing** to do with wasm-git, it is a BROWSER restriction that you will not be able to access Github via Https if they do not set CORS headers, which they don't.

It has nothing to do with using WASM or JS, these are web browser security restrictions. So yes, you *will* need  a proxy if you intend to use Github hosted repos with wasm-git or any other git client in a web browser. If this doesn't work for your use case, then you may want to look at using Githubs proprietary REST or GraphQL APIs.

As an aside I and others asked for this from [Bitbucket back in 2014 and they said no](https://jira.atlassian.com/browse/BCLOUD-8846). Afaik Github don't even have a place to where you can request this, so I'm not very confident they would ever even consider it.

**Comment by kgzoom** [comment]
Thanks for your patience @petersalomonsen.

Ok, so if I understand: Because you are in control of CORS in your browser app, peer-to-peer push/pull/clone will be possible from one browser node to another browser node because as the app developer you can set CORS policy in each browser? I'm new to all this, but that's what I need to know before I dedicate my time to learning all about Wasm and browser tech. I need confirmation that at least peer-to-peer, app-to-app, browser-to-browser is possible.

**Comment by kgzoom** [comment]
And if "node/app/browser to GitHub" is not possible because you don't have control of the CORS headers of GitHub, then I'm still going to go through with this project because the real use case I'm interested in is peer-to-peer where each peer uses the same codebase.

**Comment by maks** [comment]
That last reply was from me, @maks not Peter.

In regards to peer-to-peer, I don't know if its even possible to have a browser hosted http server, but that it really getting off topic here, for that you may be better off asking questions on stackoverflow and looking [at existing answers there](https://stackoverflow.com/a/24252484/85472).

**Comment by kgzoom** [comment]
Ok, thanks @petersalomonsen

**Comment by petersalomonsen** [comment]
thanks @maks, you provided good answers here :)

**Comment by SaadBazaz** [comment]
Hey @maks ,
I have an idea; What if we used server-side rendering to send the requests to GitHub? 

For example, in NextJS we could do Git operations like add, commit etc, on the **browser,** and the other network-based operations like pull, push, fetch etc on the server-side.

Do you think that's possible? Eager to hear what you have to say.

**Comment by petersalomonsen** [comment]
> For example, in NextJS we could do Git operations like add, commit etc, on the **browser,** and the other network-based operations like pull, push, fetch etc on the server-side.

This is what's going on here, pull / push / fetch is proxied through the server, and forwarded to github:

https://github.com/petersalomonsen/wasm-git/blob/master/examples/webserverwithgithubproxy.js

**Comment by SaadBazaz** [comment]
> > For example, in NextJS we could do Git operations like add, commit etc, on the **browser,** and the other network-based operations like pull, push, fetch etc on the server-side.
> 
> This is what's going on here, pull / push / fetch is proxied through the server, and forwarded to github:
> 
> https://github.com/petersalomonsen/wasm-git/blob/master/examples/webserverwithgithubproxy.js

Yeah I realized that soon after. This is a super cool idea. This "http server" could be a serverside route in frameworks like Next. So one app -> a fully working wasm-git implementation. 

I am trying out the above, but a quick question;

What do I even send to the proxy? How do I query it / use it from the browser?

**Comment by petersalomonsen** [comment]
> What do I even send to the proxy? How do I query it / use it from the browser?

You just set it as a remote like you would do with regular git from the terminal ( in fact you can push to this proxy from the terminal too ).

Here's how to set a remote: https://github.com/petersalomonsen/wasm-git/blob/master/test-browser/remote.spec.js#L62

or even just clone a repo directly like from the example here:

https://github.com/petersalomonsen/wasm-git/blob/master/examples/example_webworker.js#L16

Through this wasm-git in the browser can talk directly to github (or any other git-server)
