### ISSUE TITLE
Does wasm-git support custom File System?

### ISSUE THREAD

**Issue by sinoon** [petersalomonsen/wasm-git#48]
# Background

I know we can use four type file system with emscripten, MEMFS / NODEFS / IDBFS / WORKERFS / PROXYFS.
But I have a cross-process File System（Compatible Node.js FS） for Browser, it can share multiple workers.

# Question
can I provider my custom File System for wasm-git?

**Comment by petersalomonsen** [comment]
wasm-git has only been tested with MEMFS, IDBFS and NODEFS, and it just use the Emscripten provided file system out of the box. If you can plug your custom file system into emscripten, and that filesystem implements the Emscripten file system API ( https://emscripten.org/docs/api_reference/Filesystem-API.html ) ,  there's a chance it might work, but this has never been tested.
