### ISSUE TITLE
Clone arguments `--depth 1` not working with `lg.callMain(['clone', url, dir, '--depth', '1'])`

### ISSUE THREAD

**Issue by tiagobento** [petersalomonsen/wasm-git#52]
Currently trying to experiment the performance of `wasm-git` for not-so-small Git repositories, but using `--depth 1` on a `clone` call doesn't seem to have any effect. Any idea what could be happening?

What I did was I modified the `githttpserver` to not add an Authorization header to HTTP requests and used [Isomorphic Git's CORS proxy](https://github.com/isomorphic-git/cors-proxy) to bypass CORS restrictions to GitHub. So from my `localhost`, I try to download any fairly-sized GitHub repository, and it takes forever, even with `--depth 1`.

Let me know if I can help fixing this!

**Comment by tiagobento** [comment]
Looks like I had some reading to do before opening this issue :)

Just found that `lg.callMain` is actually deferring to `examples/lg2.c`'s main, which then calls libgit2's clone function. Also, shallow clones as not supported by libgit2 (as per https://github.com/libgit2/libgit2/issues/3058), so closing this issue.

**Comment by DanilKazanov** [comment]
Shallow clone is now supported =)

**Comment by petersalomonsen** [comment]
wasm-git is now up to date with the latest libgit2

**Comment by DanilKazanov** [comment]
> wasm-git is now up to date with the latest libgit2

Where I can see api docs? I tried to use `lg.callMain(["clone", url, dir, "--depth", "1", ])`, and it looks like it's not working.

**Comment by petersalomonsen** [comment]
at this point wasm-git expose the examples from libgit2, and then you need to modify this file here: https://github.com/libgit2/libgit2/blob/main/examples/clone.c so that it can accept the depth argument ( or just set the `clone_opts.fetch_opts.depth` property directly to what you want ).

however there's also a new cli in libgit2 that I would like to add support for and it seems it also does handle depth:

https://github.com/libgit2/libgit2/blob/main/src/cli/cmd_clone.c

CLI support is on my todo list.

**Comment by kkoomen** [comment]
@petersalomonsen is there a lg2.wasm that supports this? because as of today, the lg2.js from the demo site does not provide the depth argument, which I do need.

**Comment by petersalomonsen** [comment]
> @petersalomonsen is there a lg2.wasm that supports this? because as of today, the lg2 from the demo site does not provide the depth argument, which I do need.

There is not yet a lg2.wasm that has the cli, which is preferred when introducing new standard features. If you need it now, the best would be to implement it in C and compile your own lg2.wasm.
