### ISSUE TITLE
Emulate git cli in browser

### ISSUE THREAD

**Issue by iliakan** [petersalomonsen/wasm-git#61]
Can I use this library to emulate git cli in browser, e.g. to act as a git playground?

So that the user may `git init`, run git commands, etc.

How difficult does that appear to implement (in git-related part)?

**Comment by petersalomonsen** [comment]
Here you can see from the webworker example code several commands being executed:

https://github.com/petersalomonsen/wasm-git/blob/master/examples/example_webworker.js#L16

I guess you could build on this to emulate a cli?

**Comment by iliakan** [comment]
Looks like I bumped into the limitations of libgit2.

E.g. it suggests that I call `init` with a required directory.
Also it doesn't allow `commit -a` flag.

There's more differences, I guess.
