### ISSUE TITLE
Rebuilding on MacOS for development

### ISSUE THREAD

**Issue by iliakan** [petersalomonsen/wasm-git#63]
Let's say I want to create new commands.

I follow these steps for the initial build:

```bash
npm install
sh setup.sh
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
cd ..
source ./emsdk/emsdk_env.sh
cd emscriptenbuild
./build.sh Release
```

Is it correct? Should I use Release?

Also, on changes, should I re-run `./build.sh Release` to get a new build?

**Comment by petersalomonsen** [comment]
that looks very much like what happens in the build pipeline ( https://github.com/petersalomonsen/wasm-git/blob/master/.github/workflows/main.yml#L24 ), which does work.

You don't need to build with the `Release` flag in development, actually you better not if you want to trace errors.

I also use Mac for development.
