### ISSUE TITLE
How to do a git clone to be used from memfs + questions about global variables

### ISSUE THREAD

**Issue by nikitavoloboev** [petersalomonsen/wasm-git#68]
I am trying to expose wasm-git as a raw interface similar to https://isomorphic-git.org/en/

I have this file:

https://github.com/nikitavoloboev/inlang/blob/libgit2/source-code/git-sdk/src/api/index.ts#L4

Trying to base it off https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitworker.js

I get lots of TS issues as it doesn't know what `FS` means, it's a global variable, not sure where is it defined?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/6391776/223195437-c27e599b-3806-44df-a8e6-3525bb534a0a.png">

In the end I would essentially do a call similar to

```
	await raw.clone({
		fs: args.fs,
		http,
		dir: "/",
		corsProxy: clientSideEnv.VITE_GIT_REQUEST_PROXY_PATH,
		url: `https://${host}/${owner}/${repository}`,
	})
```

But with exposed wasm-git.

Also I see ` lg.callMain(['clone',`http://localhost:5000/test.git`, 'testrepo']);` used in example but it doesn't seem to accept as argument a file system, is this possible to pass?

I essentially want to do a `git clone` with wasm-git to be used from https://www.npmjs.com/package/memfs

For `FS` issue, I at first thought I should do `import FS = require('fs');` but [wasmgitworker.js](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitworker.js) didn't have it so not sure.

Thanks for any help on this. ♥️

**Comment by nikitavoloboev** [comment]
In the end I would essentially do a call similar to

```
	await raw.clone({
		fs: args.fs,
		http,
		dir: "/",
		corsProxy: clientSideEnv.VITE_GIT_REQUEST_PROXY_PATH,
		url: `https://${host}/${owner}/${repository}`,
	})
```

But with wasm-git.

There is ` lg.callMain(['clone',`http://localhost:5000/test.git`, 'testrepo']);` as example but it doesn't seem to accept as argument a file system, is this possible to pass?

**Comment by nikitavoloboev** [comment]
Trying to port this file https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitworker.js to work but it also uses `FS` I guess I should just try run it in browser and it would work.

**Comment by petersalomonsen** [comment]
`FS` is a global object when loading an emscripten build. So when you have loaded `lg2.js` (using `importScripts` in a web worker) you should have `FS` on the global scope. `FS` is the File System API of emscripten: https://emscripten.org/docs/api_reference/Filesystem-API.html

For using in TypeScript you should just declare it as `any`, unless you find any good type definitions for it (I'm sure there are many out there).

**Comment by nikitavoloboev** [comment]
Okay so I tried to put it in a web worker.

I have a project here: https://github.com/nikitavoloboev/try/tree/main/solid

It uses [Solid](https://www.solidjs.com) as framework so I found a way to run web workers with it:

https://www.npmjs.com/package/@solid-primitives/workers

However I get an issue when I try to just put the code from `readme.md` into it:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/6391776/223274975-c66d535b-8d23-4d8f-8054-0ea1384c67ba.png">

**Comment by nikitavoloboev** [comment]
Thank you.

I think I am starting to figure out the web worker side of things.

https://github.com/nikitavoloboev/try/blob/main/solid/src/worker.js

Stuck trying to do a sparse clone with libgit. 

I think I need something like

`lg.callMain(["clone", "--depth=1", msg.data.repo])`

But for some reason if I keep my worker simple like:

```
onmessage = function (e) {
  console.log("Worker: Message received from main script");
  const result = e.data[0] * e.data[1];
  if (isNaN(result)) {
    postMessage("Please write two numbers");
  } else {
    const workerResult = "Result: " + result;
    console.log("Worker: Posting message back to main script");
    postMessage(workerResult);
  }
};
```

All works.

But when I add code with libgitPromise as in [wasmworker.js](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/wasmgit/wasmgitworker.js)

All stops working. I am not sure what I am missing.

**Comment by nikitavoloboev** [comment]
https://github.com/petersalomonsen/wasm-git/blob/master/examples/example_webworker.js

This file looks very simple and does close to what I want only thing I don't have the `lg2.js` file. I guess it's because I can't do steps build.sh in #67 issue. Not sure.

**Comment by nikitavoloboev** [comment]
https://github.com/petersalomonsen/wasm-git/blob/master/examples/example_webworker.js

This file look simple and does close to what I want only thing I don't have the `lg2.js` file locally. I guess it's because I can't do steps build.sh in #67 issue. 

And I can't seem to get it through the `const WASM_GIT_BASE_URL = "https://unpkg.com/wasm-git@0.0.9/"` url. Web worker breaks for me. 😞

**Comment by nikitavoloboev** [comment]
I just realize I can perhaps get the raw .js and .wasm files from https://unpkg.com/browse/wasm-git@0.0.9/

Will try that as getting it straight from unkpg causes errors for me.

**Comment by nikitavoloboev** [comment]
What I got to so far: https://github.com/nikitavoloboev/try/blob/main/solid/src/worker.js

Added comments to where I am confused how to do some things. I manually moved the `lg.js` to repo. 

I am trying to understand how to add the github proxy thing so the clone works with CORS using new wasm-git syntax and not sure about some git clone commands, it's kind of hard to test.

**Comment by petersalomonsen** [comment]
Hi,

I've reduced your WebWorker code to a minimum for cloning, in order to just hopefully make it possible for you to clone your repo. As you can see below, I'm loading `lg2.js` from unpkg.com (where they are prebuilt as a result of publishing  to npm). 

So this would be your minimum WebWorker code ( place it in a js file and load it using `new Worker('workerfile.js')`  ).

This clones via localhost, where your proxy for github should be running ( code for the proxy is under the worker code ).

```
const WASM_GIT_BASE_URL = 'https://unpkg.com/wasm-git@0.0.9/';
var Module = {
  locateFile: function (s) {
    return WASM_GIT_BASE_URL + s;
  },
  'print': function (text) {
    console.log(text);
  },
  'printErr': function (text) {
    console.error(text);
  }
};

importScripts(WASM_GIT_BASE_URL+"lg2.js");

// from my understanding, this is needed to check the module got loaded properly
const libgitPromise = new Promise((resolve) => {
  Module.onRuntimeInitialized = () => {
    resolve(Module);
  }
});

(async () => {
  const libgit = await libgitPromise;

  
  FS.mkdir("/test");
  FS.mount(MEMFS, {}, "/test");
  FS.chdir("/test");

 
  libgit.callMain(["clone", "http://localhost:5002/nikitavoloboev/try", "try"]);
  FS.chdir("try");
})()
```;

And here is the code for the proxy which you can run using nodejs:

```
const http = require('http');
const https = require('https');

function onRequest(request, response) {
    let path = request.url.substring(1);
    console.log(path);

    response.setHeader('Access-Control-Allow-Origin', '*');
    response.setHeader('Access-Control-Allow-Headers', '*');

    if( path.indexOf('git-upload') > -1 ||
        path.indexOf('git-receive') > -1) {  
        const options = {
            hostname: 'github.com',
            port: 443,
            path: request.url,
            method: request.method,
        };

        console.log(`Proxying ${options.method} request to ${options.hostname} with path ${options.path}`);
        const proxy = https.request(options, function (res) {
            res.pipe(response, {
            end: true
            });
        });

        request.pipe(proxy, {
            end: true
        });
    }
}

http.createServer(onRequest).listen(5002);
```

**Comment by nikitavoloboev** [comment]
Okay I tried that but hitting this issue:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/6391776/223526340-950b9d3a-13bd-4f2e-8ab2-29bcc90182fc.png">

My front end code here: https://github.com/nikitavoloboev/try/tree/main/solid

The code that creates the worker: https://github.com/nikitavoloboev/try/blob/main/solid/src/routes/web-workers.tsx

I added worker here: https://github.com/nikitavoloboev/try/blob/main/solid/src/workerfile.js

The issue is that the worker gets loaded but the issue is there because of this line:

https://github.com/nikitavoloboev/try/blob/main/solid/package.json#L8

The issue is that if I remove the line my solid framework breaks down as it expects things to be in modules.

Do you know if there is a es modules friendly alternative to `importScripts`?

**Comment by nikitavoloboev** [comment]
Perhaps something like 

```js
import * from 'https://unpkg.com/wasm-git@0.0.9/lg2.js'

var Module = {
  locateFile: function (s) {
    return WASM_GIT_BASE_URL + s
  },
  print: function (text) {
  ```

**Comment by petersalomonsen** [comment]
It's very important that the Module is declared before the import, otherwise it will not be applied. Do you have to create the worker with `type: 'module'` ( https://github.com/nikitavoloboev/try/blob/main/solid/src/routes/web-workers.tsx#L6 ) . If you can skip this, then my example would work better.

**Comment by nikitavoloboev** [comment]
Ok indeed removing the `type: module` removes the error. Now everything loads with no error, however I don't know how to check if it worked.

I watched [your demo of wasm-git](https://www.youtube.com/watch?v=1Hqy7cVkygU&t=221s) and in there you show IndexedDB in dev tools but for me its empty.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/6391776/223565458-f74191e2-f82e-4eb7-9621-c2eab4fbea5f.png">

**Comment by nikitavoloboev** [comment]
ah wait I do get errors

<img width="867" alt="image" src="https://user-images.githubusercontent.com/6391776/223565861-259e3b42-dc5b-4b56-a619-54b6b5c404ee.png">

**Comment by nikitavoloboev** [comment]
oh wait but I see it working

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6391776/223566057-9c80d40c-df29-445b-ae09-00bf44936a09.png">

So I guess it loaded in, just its not stored in IndexedDB.

**Comment by nikitavoloboev** [comment]
Okay I see IDBFS sits on top of MEMFS actually, according to [this answer](https://stackoverflow.com/questions/67436377/emscripten-is-idbfs-more-ram-efficient-than-memfs). 

Thanks a lot again.
