### ISSUE TITLE
How can I use my credentials to clone/pull/push to a private repo?

### ISSUE THREAD

**Issue by yxshv** [petersalomonsen/wasm-git#92]
Is there any way, I can give it my github access token?

**Comment by yxshv** [comment]
I found this https://github.com/petersalomonsen/wasm-git/issues/72 , but it is not working in nodejs

**Comment by yxshv** [comment]
I tried add interceptors using [`@mswjs/interceptors`](https://github.com/mswjs/interceptors) but it didn't work :/

**Comment by yxshv** [comment]
I got it working...

I had to edit the `lg2.js` file to manually set an `Authorization` header from a environmental variables... and it worked

but there should be a better way...?

**Comment by petersalomonsen** [comment]
You don't need to edit `lg2.js` manually. Take a look at how it is done here: https://github.com/petersalomonsen/githttpserver/blob/master/public/libgit2_webworker.js#L17

**Comment by yxshv** [comment]
> You don't need to edit `lg2.js` manually. Take a look at how it is done here: https://github.com/petersalomonsen/githttpserver/blob/master/public/libgit2_webworker.js#L17

well now, I forked it and build it on my own

thanks tho :)
