### ISSUE TITLE
Add all files to staging

### ISSUE THREAD

**Issue by rinkesh314e** [petersalomonsen/wasm-git#96]
Hi, I had a doubt on how could i simulate `git add --all` behaviour with this module. Git add with libgit2 does not suppport `--all` argument. Any suggestions on how i could do it?

**Comment by petersalomonsen** [comment]
See how it's solved in this project using wasm-git: https://github.com/arizas/Ariz-Portfolio/blob/main/public_html/storage/wasmgitworker.js#L121

It's using `git status` to find all the files that are updated/not tracked and then adds them.
